FROM nginx
RUN rm /usr/share/nginx/html/index.html
RUN rm /etc/nginx/nginx.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY expense.conf /etc/nginx/nginx.conf
COPY expense.conf /etc/nginx/nginx.conf
COPY code  /usr/share/nginx/html/



