version: "3"
services:
  mysql: 
   image: "mysql-v.1.0"
   volumes:
     - mysql-volume:/var/lib/mysql
   ports:
      - 3306:3306
   networks:
    - expense
  backend:
   image: "backend-v.1.0"
   ports:
    - 8080:8080
   networks:
    - expense
   depends_on:
    - mysql
  frontend:
    image: "frontend:v.1.0"
    ports:
    - 80:80
    networks:
    - expense
    depends_on:
      - backend
volumes:
     mysql-volume:
       external: false
networks: 
    expense:
     driver: bridge







   
  