version: "3"
networks: expense
services:
  mysql: 
   image: "mysql-v.1.0"
   volumes:
     - mysql-volume:/var/lib/mysql
   ports:
      - 3306:3306
   depends_on:
      - backend
  backend:
   image: "backend-v.1.0"
   ports:
    - 8080:8080
  frontend:
    image: "frontend:v.1.0"
    ports:
     80:80
volumes:
     mysql-volume:
      external: true






   
  